steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/dataanalytics-347914/python-apps/bank-campaign-model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/dataanalytics-347914/python-apps/bank-campaign-model']

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/mlevydaniel/model-training-repo.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'model-training-repo/bank_campaign_model_training.py', 'gs://us-central1-mlops-airflow-a37b7a16-bucket/dags']

images:
- 'us-central1-docker.pkg.dev/dataanalytics-347914/python-apps/bank-campaign-model'

options:
  logging: CLOUD_LOGGING_ONLY